---
title: "Data Wrangling II: Data from the Web"
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: html_document
---

```{r load packages, message = FALSE}
library(tidyverse)
library(knitr)
library(rvest)
library(httr)

opts_chunk$set(
  fig.width = 6,
  out.width = "90%"
)

## These are options that i'm going to treat as default for now
## I don't love viridis, but don't have a better option yet
theme_set(theme_bw() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Grab data from web
```{r pull in data}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```


### Pull <table> from html file
```{r pull in nsduh}
df_marj_use <- nsduh_html |> 
  html_table() |> 
  first() |> 
  slice(-1)

# first() pulls first element of list
# slice() removes first row of a df
```

There are many issues with this df, but it's now in R, and we can use str/factor approaches.

### Import Star Wars Data

```{r pull in swm}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)
```

```{r star wars movies}
vec_swm_title <- swm_html |> 
  html_elements(".lister-item-header a") |> 
  html_text()

vec_swm_gross_rev <- swm_html |> 
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |> 
  html_text()

df_swm <- tibble(
  title = vec_swm_title,
  gross_rev = vec_swm_gross_rev
)
```


## Using APIs

### Water data from NYC
```{r}
df_nyc_water = GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()
```

### BRFSS
```{r}
df_brfss <- 
  GET(
    "https://data.cdc.gov/resource/acme-vg9e.csv", 
    query = list("$limit" = 5000)) |> 
  content("parsed")

# limits are often set to prevent you pulling too much data
```

### Pokémon

```{r}
df_poke <- GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```


### Fable

```{r df}

fable_url = "http://dnd.levcprtraining.com/people.php"

fable_html = read_html(fable_url)

df_fable <- fable_html |> 
  html_table() |> 
  nth(1)

df_fable
```

